/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CacheResponseDto
 */
export interface CacheResponseDto {
    /**
     * 
     * @type {number}
     * @memberof CacheResponseDto
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'timeStamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'desc'?: string;
    /**
     * 
     * @type {number}
     * @memberof CacheResponseDto
     */
    'lat'?: number;
    /**
     * 
     * @type {number}
     * @memberof CacheResponseDto
     */
    'lng'?: number;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'imageFilename'?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'userName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CacheResponseDto
     */
    'userId'?: string;
}

