/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CacheRequestDto } from '../models';
// @ts-ignore
import type { CacheResponseDto } from '../models';
/**
 * CacheEndpointApi - axios parameter creator
 * @export
 */
export const CacheEndpointApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCacheById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCacheById', 'id', id)
            const localVarPath = `/api/caches/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} north 
         * @param {number} east 
         * @param {number} south 
         * @param {number} west 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCachesInArea: async (north: number, east: number, south: number, west: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'north' is not null or undefined
            assertParamExists('getCachesInArea', 'north', north)
            // verify required parameter 'east' is not null or undefined
            assertParamExists('getCachesInArea', 'east', east)
            // verify required parameter 'south' is not null or undefined
            assertParamExists('getCachesInArea', 'south', south)
            // verify required parameter 'west' is not null or undefined
            assertParamExists('getCachesInArea', 'west', west)
            const localVarPath = `/api/caches/map/{north}/{east}/{south}/{west}`
                .replace(`{${"north"}}`, encodeURIComponent(String(north)))
                .replace(`{${"east"}}`, encodeURIComponent(String(east)))
                .replace(`{${"south"}}`, encodeURIComponent(String(south)))
                .replace(`{${"west"}}`, encodeURIComponent(String(west)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} filename 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImage: async (filename: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'filename' is not null or undefined
            assertParamExists('getImage', 'filename', filename)
            const localVarPath = `/api/caches/images/{filename}`
                .replace(`{${"filename"}}`, encodeURIComponent(String(filename)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CacheRequestDto} cacheRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCache: async (cacheRequestDto: CacheRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cacheRequestDto' is not null or undefined
            assertParamExists('postCache', 'cacheRequestDto', cacheRequestDto)
            const localVarPath = `/api/caches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(cacheRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CacheEndpointApi - functional programming interface
 * @export
 */
export const CacheEndpointApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CacheEndpointApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCacheById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CacheResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCacheById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheEndpointApi.getCacheById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} north 
         * @param {number} east 
         * @param {number} south 
         * @param {number} west 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCachesInArea(north: number, east: number, south: number, west: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<CacheResponseDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCachesInArea(north, east, south, west, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheEndpointApi.getCachesInArea']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} filename 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getImage(filename: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getImage(filename, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheEndpointApi.getImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CacheRequestDto} cacheRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postCache(cacheRequestDto: CacheRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CacheResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postCache(cacheRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CacheEndpointApi.postCache']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CacheEndpointApi - factory interface
 * @export
 */
export const CacheEndpointApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CacheEndpointApiFp(configuration)
    return {
        /**
         * 
         * @param {CacheEndpointApiGetCacheByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCacheById(requestParameters: CacheEndpointApiGetCacheByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<CacheResponseDto> {
            return localVarFp.getCacheById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CacheEndpointApiGetCachesInAreaRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCachesInArea(requestParameters: CacheEndpointApiGetCachesInAreaRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CacheResponseDto>> {
            return localVarFp.getCachesInArea(requestParameters.north, requestParameters.east, requestParameters.south, requestParameters.west, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CacheEndpointApiGetImageRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getImage(requestParameters: CacheEndpointApiGetImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getImage(requestParameters.filename, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CacheEndpointApiPostCacheRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postCache(requestParameters: CacheEndpointApiPostCacheRequest, options?: RawAxiosRequestConfig): AxiosPromise<CacheResponseDto> {
            return localVarFp.postCache(requestParameters.cacheRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CacheEndpointApi - interface
 * @export
 * @interface CacheEndpointApi
 */
export interface CacheEndpointApiInterface {
    /**
     * 
     * @param {CacheEndpointApiGetCacheByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApiInterface
     */
    getCacheById(requestParameters: CacheEndpointApiGetCacheByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<CacheResponseDto>;

    /**
     * 
     * @param {CacheEndpointApiGetCachesInAreaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApiInterface
     */
    getCachesInArea(requestParameters: CacheEndpointApiGetCachesInAreaRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<CacheResponseDto>>;

    /**
     * 
     * @param {CacheEndpointApiGetImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApiInterface
     */
    getImage(requestParameters: CacheEndpointApiGetImageRequest, options?: RawAxiosRequestConfig): AxiosPromise<object>;

    /**
     * 
     * @param {CacheEndpointApiPostCacheRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApiInterface
     */
    postCache(requestParameters: CacheEndpointApiPostCacheRequest, options?: RawAxiosRequestConfig): AxiosPromise<CacheResponseDto>;

}

/**
 * Request parameters for getCacheById operation in CacheEndpointApi.
 * @export
 * @interface CacheEndpointApiGetCacheByIdRequest
 */
export interface CacheEndpointApiGetCacheByIdRequest {
    /**
     * 
     * @type {number}
     * @memberof CacheEndpointApiGetCacheById
     */
    readonly id: number
}

/**
 * Request parameters for getCachesInArea operation in CacheEndpointApi.
 * @export
 * @interface CacheEndpointApiGetCachesInAreaRequest
 */
export interface CacheEndpointApiGetCachesInAreaRequest {
    /**
     * 
     * @type {number}
     * @memberof CacheEndpointApiGetCachesInArea
     */
    readonly north: number

    /**
     * 
     * @type {number}
     * @memberof CacheEndpointApiGetCachesInArea
     */
    readonly east: number

    /**
     * 
     * @type {number}
     * @memberof CacheEndpointApiGetCachesInArea
     */
    readonly south: number

    /**
     * 
     * @type {number}
     * @memberof CacheEndpointApiGetCachesInArea
     */
    readonly west: number
}

/**
 * Request parameters for getImage operation in CacheEndpointApi.
 * @export
 * @interface CacheEndpointApiGetImageRequest
 */
export interface CacheEndpointApiGetImageRequest {
    /**
     * 
     * @type {string}
     * @memberof CacheEndpointApiGetImage
     */
    readonly filename: string
}

/**
 * Request parameters for postCache operation in CacheEndpointApi.
 * @export
 * @interface CacheEndpointApiPostCacheRequest
 */
export interface CacheEndpointApiPostCacheRequest {
    /**
     * 
     * @type {CacheRequestDto}
     * @memberof CacheEndpointApiPostCache
     */
    readonly cacheRequestDto: CacheRequestDto
}

/**
 * CacheEndpointApi - object-oriented interface
 * @export
 * @class CacheEndpointApi
 * @extends {BaseAPI}
 */
export class CacheEndpointApi extends BaseAPI implements CacheEndpointApiInterface {
    /**
     * 
     * @param {CacheEndpointApiGetCacheByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApi
     */
    public getCacheById(requestParameters: CacheEndpointApiGetCacheByIdRequest, options?: RawAxiosRequestConfig) {
        return CacheEndpointApiFp(this.configuration).getCacheById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CacheEndpointApiGetCachesInAreaRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApi
     */
    public getCachesInArea(requestParameters: CacheEndpointApiGetCachesInAreaRequest, options?: RawAxiosRequestConfig) {
        return CacheEndpointApiFp(this.configuration).getCachesInArea(requestParameters.north, requestParameters.east, requestParameters.south, requestParameters.west, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CacheEndpointApiGetImageRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApi
     */
    public getImage(requestParameters: CacheEndpointApiGetImageRequest, options?: RawAxiosRequestConfig) {
        return CacheEndpointApiFp(this.configuration).getImage(requestParameters.filename, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CacheEndpointApiPostCacheRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CacheEndpointApi
     */
    public postCache(requestParameters: CacheEndpointApiPostCacheRequest, options?: RawAxiosRequestConfig) {
        return CacheEndpointApiFp(this.configuration).postCache(requestParameters.cacheRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

